


# This is a basic workflow to help you get started wname: selenium

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0 7 * * *'
  watch:
    types: [started]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7
      - name: 'Install requirements'
        run: pip3.7 install -r requirements.txt
      - uses: nanasess/setup-chromedriver@master
        with:
        # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: 'Working'
        run: |
          python3.7 run.py
        env:
          TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
          TG_USER_ID:  ${{secrets.TG_USER_ID}}    # tg通知id
          USER: ${{secrets.USER}}
          PASSWORD: ${{secrets.PASSWORD}}
          INVITECODE: ${{secrets.INVITECODE}}
